"""Temp table

Revision ID: 57ae4ec794ac
Revises: 
Create Date: 2019-06-29 17:37:06.338602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ae4ec794ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_temp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_target_temp'), 'temp', ['target_temp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_target_temp'), table_name='temp')
    op.drop_table('temp')
    # ### end Alembic commands ###
